### ISSUE TITLE
[Suggestion]: In some versions, switching armor with right-click doesn’t work with Elytra.

### ISSUE THREAD

**Issue by JAX081** [Fuzss/armorquickswap#3]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

It seems that right-clicking to equip or swap armor does not work when using an Elytra. I’m not sure if this behavior is intentional or a bug.

Versions Tested:

1.20.1 – Fabric and Forge → Issue occurs

1.21.1 – NeoForge and Fabric → Issue occurs

1.21.8 – NeoForge → Issue does not occur

I have confirmed that the latest version of the mod was used for each corresponding Minecraft version and mod loader.

If this isn’t a bug and it’s a feature that’s still in development, sorry for the inconvenience.

**Comment by Fuzss** [comment]
Fixed for 1.21.1 now. Don't really have any plans to support 1.20.1 for this anymore.
Thanks for investigating!

**Comment by JAX081** [comment]
Hello! Since you mentioned that you weren’t planning to update the mod to version 1.20.1, I took the liberty of doing it myself. If for any reason you don’t want this version to remain public or would prefer me to take it down, just let me know.

You’re completely free to use the code from the fork I’ve uploaded to my GitHub. Of course, I’m aware of the license under which I’ve been modifying the code and, as I understand it, making the source code public is required, so it’s included in my fork (or however you’d phrase duplicating your repo).

I wanted to create a Fabric modpack for 1.20.1, so I couldn’t wait and decided to modify it on my own… and it ended up working.

I also make it clear in the README that you are the original creator, and I ask users not to open issues in the original repository if they are using my modified version.

I also wanted to ask: if you’re not planning to release an official version with the fix for 1.20.1, would you be okay with me publishing the mod on CurseForge or Modrinth? Of course, I would give you full credit as the original author and clearly label it as an unofficial backport/fork (I’m not entirely sure about the exact term).

**Comment by JAX081** [comment]
While I was editing the code I uploaded to GitHub, I accidentally (still not sure how) sent a pull request to your repo, and on top of that it was wrong because I modified the code of a file I shouldn’t have lol.
